env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  {
    linebreak-style: ['error', 'windows'],
    no-console: off,
    object-curly-spacing: off,
    object-curly-newline: off,
    no-underscore-dangle: off,
    no-plusplus: off,
    no-param-reassign: off,
    class-methods-use-this: off,
    implicit-arrow-linebreak: off,
    arrow-body-style: off,
    no-template-curly-in-string: off,
    one-var: off,
    no-loop-func: off,
    comma-dangle: off,
    one-var-declaration-per-line: off,
    indent: off,
    operator-linebreak: off,
    no-shadow: off,
  }
